name: Android APK Build and Release

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > keystore.jks
          mv keystore.jks release-key.jks

      - name: Verify Keystore File
        run: ls -la release-key.jks

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Build Signed APK
        run: |
          export KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          export KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          export KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          ./gradlew clean assembleRelease

      - name: Debug Build Output
        run: ls -R app/build/outputs/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          generate_release_notes: false
          make_latest: true
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}

